### ISSUE TITLE
Should percentLift/credInt args to generics be named?

### ISSUE THREAD

**Issue by FrankPortman** [FrankPortman/bayesAB#2]
I think these args should be named lists/vectors in order to not be ambiguous.

Alternatively, we can make them constant (scalar) for a single invocation of plot/summary. However this is less flexible.

**Comment by JesseKolb** [comment]
I think for the printing it is fine that the args are not named since you have to call the name of the argument to access the value anyways.  Are you referring to the name being passed from the variable to the x-label when using the plot method?  I noticed that the x-axis is unlabeled now.

**Comment by FrankPortman** [comment]
In both summary/plot you have to pass in a percentLift/credInt list/vector that is the same length as the number of params you are building posteriors for. If they are unnamed then it's simply order based.

**Comment by Lily-to** [comment]
I am very appreciate that you give this code,but  when I run it ,I have some questions,could you please give me the data,thank you very much!
