### ISSUE TITLE
Update rule in drawMusAndSigmas of dist-normal.R seems incorrect

### ISSUE THREAD

**Issue by camdenhu** [FrankPortman/bayesAB#24]
Your code does not correspond to the update rule in https://en.wikipedia.org/wiki/Conjugate_prior, which is the same as https://www.cs.ubc.ca/~murphyk/Papers/bayesGauss.pdf under a different parameterization.

Another problem: when sampling from the gamma distribution, the default arguments have rate as the third argument instead of shape. You would need to name your shape argument.

Great package overall. Thanks for the great work.

**Comment by FrankPortman** [comment]
Hi,

Thanks for your comment.

For your first problem, could you please flesh that out a bit more? Perhaps with a pull request or reproducible example so we can discuss further?

For your second problem, I'm also not entirely sure what you mean. Are you referring to using the `gamma` distributions for calculating the `invgamma` distributions? If so, the `scale` parameter of the Inverse Gamma distribution actually corresponds to the `beta`/`rate` parameter of the Gamma, so using the scale param of `invgamma` in the `rate` position of the `gamma` function is correct.

**Comment by camdenhu** [comment]
I have submitted a pull request with the update rule I believe to be correct, changing the notations at the same time.

I think that you are right about my second question. I have decided to specify the scale parameter of the gamma distribution to be the inverse of the scale parameter of the inverse gamma distribution, which is clearer to me.

**Comment by FrankPortman** [comment]
Thanks for this. I am actually working on a broader PR that addresses your concerns as well:

https://github.com/FrankPortman/bayesAB/pull/27

Feel free to comment on that too.
