### ISSUE TITLE
Get Posterior Error Function

### ISSUE THREAD

**Issue by Salma-Bouzid** [FrankPortman/bayesAB#30]
Can you explain how does this function work? When I try running it on two dummy vectors, I get an Inf. 
Do A_samples and B_samples encode the entire data vectors? Is this the squared loss? Can you explain the logic behind this implementation? What does loss do if A_samples and B_samples have 0s?
I highlighted the unclear code snipets. 
`set.seed(1)
 a <- rbinom(100, 1, .5)
 b <- rbinom(100, 1, .6)
coalesce <- function(n) ifelse(is.na(n) | is.nan(n), 0, n)

# Expected loss from switching from B to A
getPostError <- function(A_samples, B_samples, f = function(a, b) (a-b)/b) {
  BoverA <- B_samples > A_samples
  **loss <- f(B_samples, A_samples)
  coalesce(mean(BoverA) * mean(loss[BoverA]))**
}
getPostError(b,a)`

How does `summary(bayesTest(a,b, priors = c('alpha' = 1, 'beta' = 1), n_samples = 1e5, distribution = 'bernoulli'))` reach a posterior loss of 0.260855 ?

Thank you very much for making this clear.

**Comment by FrankPortman** [comment]
In `bayesTest`, the `A_data` and `B_data` refer to the input data samples. Inside `summary.bayesTest` or the `getPostError` function you linked, `A_samples` and `B_samples` refer to draws from the samples **on the parameters**. In the case of a `bernoulli` or `binomial` RV that is the `p` parameter. A more accurate test given your data is to do:

```
a2 <- rbeta(1e5, sum(a) + 1, length(a) - sum(a) + 1)
b2 <- rbeta(1e5, sum(b) + 1, length(b) - sum(b) + 1)

getPostError(b2, a2)
```

The definition of Bayesian Loss is outside the scope of this issue imo. I've implemented one type of common loss here and you can find more generic info [here](https://en.wikipedia.org/wiki/Bayes_estimator). 

It's possible that the arguments in my private functions could be more clear but they are not meant to be used directly as is. I have discussed opening up the loss API to allow user supplied losses but have not gotten around to it. I would review PRs on both variable naming and the API I mentioned if you're interested in contributing.
