### ISSUE TITLE
Posterior Expected Loss backwards?

### ISSUE THREAD

**Issue by evanhaldane** [FrankPortman/bayesAB#38]
I believe 

https://github.com/FrankPortman/bayesAB/blob/515a139a41d5d8e208a7442e66fa49ba44d7dd04/R/generics.R#L188

should be:

> Posterior Expected Loss for choosing **A** over **B**

If I'm not mistaken, the number comes from:

https://github.com/FrankPortman/bayesAB/blob/515a139a41d5d8e208a7442e66fa49ba44d7dd04/R/util.R#L16

Do I have that right? If so I can submit the one-line PR.

**Comment by FrankPortman** [comment]
Good catch. You are right. I would accept any PR making this more clear :).
