### ISSUE TITLE
Run Simulations in Parallel

### ISSUE THREAD

**Issue by smartpartrol** [FrankPortman/bayesAB#6]
Is it possible to run BayesTest in parallel?

Looking for way to run 1M permutations faster.

**Comment by FrankPortman** [comment]
Could you please provide some more details around what you wish to do. Do you mean that you want to run `bayesTest` with `n_samples = 1e6`?

**Comment by smartpartrol** [comment]
Right. Run at 1e6 on Beta Binom in parallel - rather than sequential. 

I took a look at: [dist-bernoulli.R](https://github.com/FrankPortman/bayesAB/blob/master/R/dist-bernoulli.R)

Looks like it's using vanilla `rbeta`. I will try setting up `foreach` and `doParellel` on it.

**Comment by FrankPortman** [comment]
This is vectorized and runs in <1s on my laptop. Is this a bottleneck to your workflow? I suspect trying to do it in parallel will actually slow you down - unless I'm still not understanding the question correctly. 

    library(bayesAB)

    A_binom <- rbinom(100, 1, .5)
    B_binom <- rbinom(100, 1, .6)

    AB1 <- bayesTest(A_binom, 
                     B_binom, 
                     priors = c('alpha' = 1, 'beta' = 1), 
                     distribution = 'bernoulli',
                     n_samples = 1e6)

**Comment by FrankPortman** [comment]
@smartpartrol [Take a look at the following example.](https://gist.github.com/FrankPortman/0fa234910672136dac2420503898cb29)  I've added a `c` generic that can be used to concatenate posterior results from multiple `bayesTest` objects (assuming all else is equal) and return back a new `bayesTest` object.

Here is the output from that gist:

![image](https://cloud.githubusercontent.com/assets/2442871/19877414/43854df2-9f9c-11e6-911f-3d2b3ce93313.png)

We can see that this example is marginally faster with multiple threads, but doesn't seem significant even at the `1e7` level.

**Comment by FrankPortman** [comment]
Closing now as the `c` generic has been added and a multicore example has been added. It's still probably easier to just use `n_samples = 1e6` though.
